-- Schema CRM pour PostgreSQL.

CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT,
    phone TEXT,
    company TEXT,
    job_title TEXT,
    sector TEXT,
    company_size TEXT,
    last_activity_date DATE,
    deal_value NUMERIC(14, 2),
    deal_currency CHAR(3),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- le CRM peut contenir des doublons
CREATE INDEX IF NOT EXISTS contacts_email_lower_idx
    ON contacts (LOWER(email));
CREATE INDEX IF NOT EXISTS contacts_name_idx
    ON contacts (last_name, first_name);
CREATE INDEX IF NOT EXISTS contacts_company_idx
    ON contacts (company);

CREATE TABLE IF NOT EXISTS deals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES contacts (id) ON DELETE SET NULL,
    name TEXT NOT NULL,
    amount NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (amount >= 0),
    currency CHAR(3),
    stage TEXT NOT NULL DEFAULT 'prospecting'
        CHECK (stage IN ('prospecting', 'qualification', 'proposal', 'negotiation', 'won', 'lost')),
    expected_close_date DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS deals_contact_id_idx ON deals (contact_id);
CREATE INDEX IF NOT EXISTS deals_stage_idx ON deals (stage);

CREATE TABLE IF NOT EXISTS activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contact_id BIGINT REFERENCES contacts (id) ON DELETE CASCADE,
    deal_id BIGINT REFERENCES deals (id) ON DELETE SET NULL,
    activity_type TEXT NOT NULL
        CHECK (activity_type IN ('call', 'email', 'meeting', 'note', 'task')),
    subject TEXT NOT NULL,
    details TEXT,
    happened_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CHECK (contact_id IS NOT NULL OR deal_id IS NOT NULL)
);

CREATE INDEX IF NOT EXISTS activities_contact_date_idx
    ON activities (contact_id, happened_at DESC);
CREATE INDEX IF NOT EXISTS activities_deal_id_idx ON activities (deal_id);
